In [1]:
from utils import get_all
import pandas as pd
import numpy as np

df = get_all()
df["Error Class"].value_counts().reset_index().to_clipboard(index=False, sep="\t")#.to_csv("error_class_counts.txt", sep="\t")
# df.head()

GSM8K
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx
ReAct
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
llama3.2_1b.xlsx
ReWOO
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx
DP
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx
smollm2_1.7b.xlsx
ReAct
qwen3_1.7b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
ReWOO
gemma-3-27b-it.xlsx
qwen3_1.7b.xlsx
smollm2_360m.xlsx
qwen2-math_1.5b.xlsx
qwen3_0.6b.xlsx
qwen2.5_0.5b.xlsx
gemma3_1b.xlsx
deepseek-r1_1.5b.xlsx
llama3.2_1b.xlsx

In [2]:
df["Error Class"].value_counts().reset_index().rename(columns={"index": "Error", "Error Class": "Count"}).head(50)

                    Count  count
0         Wrong Reasoning   3446
1       Plan Format Error    682
2            Overthinking    330
3              Tool Error    268
4                    Loop    173
5     Plan-Solve Mismatch    156
6           Misclassified    148
7       Calculation Error     50
8          Too Few Tokens     40
9   Equation Format Error     26
10    Tool + Format Error     19
11     Declines to Answer      9

In [3]:
df["Error Type"].value_counts()

Error Type
Execution Error     4048
Structural Error     864
Tool Error           287
Misclassified        148
Name: count, dtype: int64

# Plotting of

In [2]:
df_err = df.groupby(["Method", "Model"]).agg({
    "is_correct": "mean",
}).reset_index()
# pivot to have Method as Columns
df_err = df_err.pivot_table(index=["Model"], columns="Method", values="is_correct", fill_value=np.nan).reset_index()
df_err.head(50)

/var/folders/rl/3ygx2m4n1w747bxzh4qvfjs00000gn/T/ipykernel_46543/2118110552.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_err = df_err.pivot_table(index=["Model"], columns="Method", values="is_correct", fill_value=np.nan).reset_index()

Method                    Model  Direct Prompting     ReAct     ReWOO
0         google/gemma-3-27b-it          0.981164       NaN  0.885274
1       ollama/deepseek-r1_1.5b          0.782534       NaN  0.818493
2              ollama/gemma3_1b          0.638699       NaN  0.178082
3            ollama/llama3.2_1b          0.592466  0.240000  0.133562
4        ollama/qwen2-math_1.5b          0.878425       NaN  0.006849
5           ollama/qwen2.5_0.5b          0.482877  0.244863  0.202055
6             ollama/qwen3_0.6b          0.683219  0.741438  0.573630
7             ollama/qwen3_1.7b          0.792808  0.905822  0.835616
8           ollama/smollm2_1.7b          0.580986       NaN       NaN
9           ollama/smollm2_360m          0.142123       NaN  0.085616

In [20]:
df_t = (
    df.groupby(["Method", "Model"])
    .agg({
        "is_correct": ["sum", "mean"]
    })
    .reset_index()
    .sort_values(by=("is_correct", "sum"), ascending=False)
    .reset_index(drop=True)
)
df_t

              Method                    Model is_correct
                                                     sum      mean
0   Direct Prompting    google/gemma-3-27b-it        292  0.973333
1              ReWOO    google/gemma-3-27b-it        267  0.890000
2              ReAct        ollama/qwen3_1.7b        256  0.853333
3   Direct Prompting   ollama/qwen2-math_1.5b        247  0.823333
4              ReWOO  ollama/deepseek-r1_1.5b        232  0.773333
5              ReWOO        ollama/qwen3_1.7b        223  0.743333
6   Direct Prompting  ollama/deepseek-r1_1.5b        220  0.733333
7   Direct Prompting        ollama/qwen3_1.7b        219  0.730000
8              ReAct        ollama/qwen3_0.6b        194  0.646667
9   Direct Prompting        ollama/qwen3_0.6b        183  0.610000
10  Direct Prompting         ollama/gemma3_1b        176  0.586667
11             ReWOO        ollama/qwen3_0.6b        166  0.553333
12  Direct Prompting       ollama/llama3.2_1b        152  0.506667
13  Direct Prompting      ollama/qwen2.5_0.5b        121  0.403333
14             ReAct       ollama/llama3.2_1b         72  0.240000
15             ReAct      ollama/qwen2.5_0.5b         47  0.156667
16             ReWOO      ollama/qwen2.5_0.5b         37  0.123333
17             ReWOO         ollama/gemma3_1b         34  0.113333
18             ReWOO       ollama/llama3.2_1b         12  0.040000
19             ReWOO      ollama/smollm2_360m          7  0.023333
20             ReWOO   ollama/qwen2-math_1.5b          1  0.003333

In [15]:
mean_token_usage = df.groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)
mean_token_usage

                                          mean_correct_answers  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting              0.973333
                        ReWOO                         0.890000
ollama/deepseek-r1_1.5b Direct Prompting              0.733333
                        ReWOO                         0.773333
ollama/gemma3_1b        ReWOO                         0.113333
ollama/llama3.2_1b      Direct Prompting              0.506667
                        ReAct                         0.240000
                        ReWOO                         0.040000
ollama/qwen2-math_1.5b  Direct Prompting              0.823333
                        ReWOO                         0.003333
ollama/qwen2.5_0.5b     Direct Prompting              0.386667
                        ReAct                         0.156667
                        ReWOO                         0.123333
ollama/qwen3_0.6b       Direct Prompting              0.610000
                        ReAct                         0.646667
                        ReWOO                         0.553333
ollama/qwen3_1.7b       Direct Prompting              0.730000
                        ReAct                         0.853333
                        ReWOO                         0.743333
ollama/smollm2_360m     ReWOO                         0.023333

                                          mean_input_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                    915.036667
ollama/deepseek-r1_1.5b Direct Prompting          63.633333
                        ReWOO                    761.306667
ollama/gemma3_1b        ReWOO                    805.383333
ollama/llama3.2_1b      Direct Prompting          83.260000
                        ReAct                    681.390000
                        ReWOO                    743.496667
ollama/qwen2-math_1.5b  Direct Prompting          66.633333
                        ReWOO                    532.840000
ollama/qwen2.5_0.5b     Direct Prompting          89.633333
                        ReAct                   1072.180000
                        ReWOO                    824.213333
ollama/qwen3_0.6b       Direct Prompting          68.633333
                        ReAct                    547.066667
                        ReWOO                    754.438127
ollama/qwen3_1.7b       Direct Prompting          68.633333
                        ReAct                   1266.916667
                        ReWOO                    796.993333
ollama/smollm2_360m     ReWOO                    770.476667

                                          mean_output_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                 NaN
                        ReWOO                       0.000000
ollama/deepseek-r1_1.5b Direct Prompting          621.960000
                        ReWOO                    1137.163333
ollama/gemma3_1b        ReWOO                     231.256667
ollama/llama3.2_1b      Direct Prompting          163.753333
                        ReAct                     138.446667
                        ReWOO                      85.740000
ollama/qwen2-math_1.5b  Direct Prompting          311.493333
                        ReWOO                     312.523333
ollama/qwen2.5_0.5b     Direct Prompting          313.270000
                        ReAct                     121.580000
                        ReWOO                     233.640000
ollama/qwen3_0.6b       Direct Prompting         1393.890000
                        ReAct                     680.106667
                        ReWOO                    1405.401338
ollama/qwen3_1.7b       Direct Prompting         1650.903333
                        ReAct                     865.240000
                        ReWOO                    1321.230000
ollama/smollm2_360m     ReWOO                     353.676667

                                          mean_total_tokens
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                    915.036667
ollama/deepseek-r1_1.5b Direct Prompting         685.593333
                        ReWOO                   1898.470000
ollama/gemma3_1b        ReWOO                   1036.640000
ollama/llama3.2_1b      Direct Prompting         247.013333
                        ReAct                    819.836667
                        ReWOO                    829.236667
ollama/qwen2-math_1.5b  Direct Prompting         378.126667
                        ReWOO                    845.363333
ollama/qwen2.5_0.5b     Direct Prompting         402.903333
                        ReAct                   1193.760000
                        ReWOO                   1057.853333
ollama/qwen3_0.6b       Direct Prompting        1462.523333
                        ReAct                   1227.173333
                        ReWOO                   2159.839465
ollama/qwen3_1.7b       Direct Prompting        1719.536667
                        ReAct                   2132.156667
                        ReWOO                   2118.223333
ollama/smollm2_360m     ReWOO                   1124.153333

In [16]:
df[df["is_correct"] == True].groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)

                                          mean_correct_answers  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                   1.0
                        ReWOO                              1.0
ollama/deepseek-r1_1.5b Direct Prompting                   1.0
                        ReWOO                              1.0
ollama/gemma3_1b        ReWOO                              1.0
ollama/llama3.2_1b      Direct Prompting                   1.0
                        ReAct                              1.0
                        ReWOO                              1.0
ollama/qwen2-math_1.5b  Direct Prompting                   1.0
                        ReWOO                              1.0
ollama/qwen2.5_0.5b     Direct Prompting                   1.0
                        ReAct                              1.0
                        ReWOO                              1.0
ollama/qwen3_0.6b       Direct Prompting                   1.0
                        ReAct                              1.0
                        ReWOO                              1.0
ollama/qwen3_1.7b       Direct Prompting                   1.0
                        ReAct                              1.0
                        ReWOO                              1.0
ollama/smollm2_360m     ReWOO                              1.0

                                          mean_input_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                    901.749064
ollama/deepseek-r1_1.5b Direct Prompting          59.990909
                        ReWOO                    782.146552
ollama/gemma3_1b        ReWOO                    793.911765
ollama/llama3.2_1b      Direct Prompting          76.355263
                        ReAct                    660.347222
                        ReWOO                    730.416667
ollama/qwen2-math_1.5b  Direct Prompting          64.246964
                        ReWOO                    642.000000
ollama/qwen2.5_0.5b     Direct Prompting          80.474138
                        ReAct                    948.702128
                        ReWOO                    804.189189
ollama/qwen3_0.6b       Direct Prompting          61.262295
                        ReAct                    503.561856
                        ReWOO                    785.909091
ollama/qwen3_1.7b       Direct Prompting          66.200913
                        ReAct                   1271.714844
                        ReWOO                    806.417040
ollama/smollm2_360m     ReWOO                    882.285714

                                          mean_output_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                 NaN
                        ReWOO                       0.000000
ollama/deepseek-r1_1.5b Direct Prompting          552.936364
                        ReWOO                    1023.405172
ollama/gemma3_1b        ReWOO                     268.411765
ollama/llama3.2_1b      Direct Prompting          127.282895
                        ReAct                     115.347222
                        ReWOO                      66.250000
ollama/qwen2-math_1.5b  Direct Prompting          291.004049
                        ReWOO                     381.000000
ollama/qwen2.5_0.5b     Direct Prompting          258.672414
                        ReAct                     124.893617
                        ReWOO                     291.972973
ollama/qwen3_0.6b       Direct Prompting         1101.540984
                        ReAct                     508.041237
                        ReWOO                    1068.290909
ollama/qwen3_1.7b       Direct Prompting         1504.054795
                        ReAct                     753.750000
                        ReWOO                    1059.251121
ollama/smollm2_360m     ReWOO                     189.000000

                                          mean_total_tokens
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                    901.749064
ollama/deepseek-r1_1.5b Direct Prompting         612.927273
                        ReWOO                   1805.551724
ollama/gemma3_1b        ReWOO                   1062.323529
ollama/llama3.2_1b      Direct Prompting         203.638158
                        ReAct                    775.694444
                        ReWOO                    796.666667
ollama/qwen2-math_1.5b  Direct Prompting         355.251012
                        ReWOO                   1023.000000
ollama/qwen2.5_0.5b     Direct Prompting         339.146552
                        ReAct                   1073.595745
                        ReWOO                   1096.162162
ollama/qwen3_0.6b       Direct Prompting        1162.803279
                        ReAct                   1011.603093
                        ReWOO                   1854.200000
ollama/qwen3_1.7b       Direct Prompting        1570.255708
                        ReAct                   2025.464844
                        ReWOO                   1865.668161
ollama/smollm2_360m     ReWOO                   1071.285714

In [17]:
df[df["is_correct"] == False].groupby(["Model", "Method"]).agg(
    mean_correct_answers=("is_correct", "mean"),
    mean_input_tokens=("input_tokens", "mean"),
    mean_output_tokens=("output_tokens", "mean"),
    mean_total_tokens=("total_tokens", "mean"),
)

                                          mean_correct_answers  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                   0.0
                        ReWOO                              0.0
ollama/deepseek-r1_1.5b Direct Prompting                   0.0
                        ReWOO                              0.0
ollama/gemma3_1b        ReWOO                              0.0
ollama/llama3.2_1b      Direct Prompting                   0.0
                        ReAct                              0.0
                        ReWOO                              0.0
ollama/qwen2-math_1.5b  Direct Prompting                   0.0
                        ReWOO                              0.0
ollama/qwen2.5_0.5b     Direct Prompting                   0.0
                        ReAct                              0.0
                        ReWOO                              0.0
ollama/qwen3_0.6b       Direct Prompting                   0.0
                        ReAct                              0.0
                        ReWOO                              0.0
ollama/qwen3_1.7b       Direct Prompting                   0.0
                        ReAct                              0.0
                        ReWOO                              0.0
ollama/smollm2_360m     ReWOO                              0.0

                                          mean_input_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                   1022.545455
ollama/deepseek-r1_1.5b Direct Prompting          73.650000
                        ReWOO                    690.205882
ollama/gemma3_1b        ReWOO                    806.849624
ollama/llama3.2_1b      Direct Prompting          90.351351
                        ReAct                    688.035088
                        ReWOO                    744.041667
ollama/qwen2-math_1.5b  Direct Prompting          77.754717
                        ReWOO                    532.474916
ollama/qwen2.5_0.5b     Direct Prompting          95.407609
                        ReAct                   1095.118577
                        ReWOO                    827.030418
ollama/qwen3_0.6b       Direct Prompting          80.162393
                        ReAct                    626.688679
                        ReWOO                    715.686567
ollama/qwen3_1.7b       Direct Prompting          75.209877
                        ReAct                   1239.000000
                        ReWOO                    769.701299
ollama/smollm2_360m     ReWOO                    767.805461

                                          mean_output_tokens  \
Model                   Method
google/gemma-3-27b-it   Direct Prompting                 NaN
                        ReWOO                       0.000000
ollama/deepseek-r1_1.5b Direct Prompting          811.775000
                        ReWOO                    1525.279412
ollama/gemma3_1b        ReWOO                     226.507519
ollama/llama3.2_1b      Direct Prompting          201.209459
                        ReAct                     145.741228
                        ReWOO                      86.552083
ollama/qwen2-math_1.5b  Direct Prompting          406.981132
                        ReWOO                     312.294314
ollama/qwen2.5_0.5b     Direct Prompting          347.690217
                        ReAct                     120.964427
                        ReWOO                     225.433460
ollama/qwen3_0.6b       Direct Prompting         1851.153846
                        ReAct                     995.018868
                        ReWOO                    1820.500000
ollama/qwen3_1.7b       Direct Prompting         2047.938272
                        ReAct                    1513.909091
                        ReWOO                    2079.948052
ollama/smollm2_360m     ReWOO                     357.610922

                                          mean_total_tokens
Model                   Method
google/gemma-3-27b-it   Direct Prompting                NaN
                        ReWOO                   1022.545455
ollama/deepseek-r1_1.5b Direct Prompting         885.425000
                        ReWOO                   2215.485294
ollama/gemma3_1b        ReWOO                   1033.357143
ollama/llama3.2_1b      Direct Prompting         291.560811
                        ReAct                    833.776316
                        ReWOO                    830.593750
ollama/qwen2-math_1.5b  Direct Prompting         484.735849
                        ReWOO                    844.769231
ollama/qwen2.5_0.5b     Direct Prompting         443.097826
                        ReAct                   1216.083004
                        ReWOO                   1052.463878
ollama/qwen3_0.6b       Direct Prompting        1931.316239
                        ReAct                   1621.707547
                        ReWOO                   2536.186567
ollama/qwen3_1.7b       Direct Prompting        2123.148148
                        ReAct                   2752.909091
                        ReWOO                   2849.649351
ollama/smollm2_360m     ReWOO                   1125.416382