In [1]:
from utils import get_df

df_dp = get_df()
df_dp.head()

,Method,Model,question,target_answer,response,is_correct,input_tokens,output_tokens,total_tokens,reasoning,Error Class,Tool Usage,Tool Usage Count
0,ReAct,ollama/qwen3_1.7b,Janet‚Äôs ducks lay 16 eggs per day. She eats ...,Janet sells 16 - 3 - 4 = <<16-3-4=9>>9 duck eg...,"<think>\nOkay, let's break down the problem st...",True,1320,557,1877,"[AI]: <think>\nOkay, let's see. Janet has duck...",NaN,True,1
1,ReAct,ollama/qwen3_1.7b,A robe takes 2 bolts of blue fiber and half th...,It takes 2/2=<<2/2=1>>1 bolt of white fiber\nS...,"<think>\nOkay, let's break this down. The prob...",True,1168,436,1604,"[AI]: <think>\nOkay, let's see. The problem is...",NaN,True,1
2,ReAct,ollama/qwen3_1.7b,Josh decides to try flipping a house. He buys...,The cost of the house and repairs came out to ...,"<think>\nOkay, let's break down the problem st...",True,1430,965,2395,"[AI]: <think>\nOkay, let's see. Josh bought a ...",NaN,True,1
3,ReAct,ollama/qwen3_1.7b,James decides to run 3 sprints 3 times a week....,He sprints 3*3=<<3*3=9>>9 times\nSo he runs 9*...,"<think>\nOkay, let's see. The problem says Jam...",False,1109,382,1491,"[AI]: <think>\nOkay, let's see. James runs 3 s...",misinterpretation of information,True,1
4,ReAct,ollama/qwen3_1.7b,"Every day, Wendi feeds each of her chickens th...","If each chicken eats 3 cups of feed per day, t...","<think>\nOkay, let's see. The problem is about...",True,1525,676,2201,"[AI]: <think>\nOkay, let's see. Wendi feeds he...",NaN,True,1

In [2]:
df_dp.groupby(["Model", ]).agg({
    "Tool Usage": ["sum"]
}).reset_index()

                 Model Tool Usage
                              sum
0   ollama/llama3.2_1b        297
1  ollama/qwen2.5_0.5b        282
2    ollama/qwen3_0.6b         10
3    ollama/qwen3_1.7b        213

In [3]:
# Group by Model and Tool Usage, then aggregate
result = df_dp.groupby(["Model", "Tool Usage"]).agg({
    "is_correct": ["sum", "count"]
}).reset_index()



# Flatten column names
result.columns = ["Model", "Tool Usage", "Correct_Count", "Total_Count"]

# Calculate percentage correct
result["Percentage_Correct"] = (result["Correct_Count"] / result["Total_Count"]) * 100

# pivot the DataFrame to have Tool Usage as columns and percentage correct as values
result = result.pivot(index="Model", columns="Tool Usage", values="Percentage_Correct")
result

Tool Usage               False      True
Model
ollama/llama3.2_1b    0.000000  24.242424
ollama/qwen2.5_0.5b  33.333333  14.539007
ollama/qwen3_0.6b    65.862069  30.000000
ollama/qwen3_1.7b    78.160920  88.262911

## Tool Usage Count

In [ ]:
df_dp.groupby(["Model", ]).agg({
    "Tool Usage Count": ["sum"]
}).reset_index()

                 Model Tool Usage Count
                                    sum
0   ollama/llama3.2_1b              307
1  ollama/qwen2.5_0.5b              304
2    ollama/qwen3_0.6b               11
3    ollama/qwen3_1.7b              228

In [8]:
df_dp.groupby(["Model", ]).agg({
    "Tool Usage Count": ["mean"],
}).reset_index()

                 Model Tool Usage Count
                                   mean
0   ollama/llama3.2_1b         1.023333
1  ollama/qwen2.5_0.5b         1.013333
2    ollama/qwen3_0.6b         0.036667
3    ollama/qwen3_1.7b         0.760000